[package]
name = "sample"
version = "0.1.0"
authors = ["Renjie Liu <liurenjie2008@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
